[package]
name = "decode_1720"
version = "0.1.0"
authors = ["WILLJH <ls_pulse@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
